### ISSUE TITLE
Download of the DNS Blocklist failed

### ISSUE THREAD

**Issue by jesburger55** [perplexityjeff/Windows-DNS-AdBlocker#4]
Hello,

IT guy here, I've been using your script in my home for a year or so, and it always worked great. Recently, it's been unable to download the blocklist from powershell. The web page loads fine on the server, I tried disabling firewall, av, rebooting, etc. To no avail.

Any ideas why it would just stop ?

I was using an older version of your script, but I also tried with the new one, both give errors at the same place.

![image](https://user-images.githubusercontent.com/73566787/97379111-6563c680-189a-11eb-8aa3-cb0267e99322.png)

Thanks

**Comment by perplexityjeff** [comment]
Hi, I tested the downloading function of the script by just opening a terminal but it seems to work on my end without an issue?

Could you try this maybe and see what results you get. Thank you.

![image](https://user-images.githubusercontent.com/19505844/97544646-30ef2800-19ca-11eb-837c-d265493f1705.png)

**Comment by jesburger55** [comment]
I tried copying what you wrote into PS and am getting this message.

![image](https://user-images.githubusercontent.com/73566787/97595938-9814d880-19da-11eb-9e9f-fb4254fed5a2.png)

**Comment by perplexityjeff** [comment]
Could you try entering this first and than all other commands from my screenshot. 

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

If this does fix it. You could add the line to the top of the ps1 file to fix the script. I'll edit the repo for anyone else.

**Comment by jesburger55** [comment]
That worked! <3

**Comment by jesburger55** [comment]
Hmm, when I added the line to the top of the ps1 file I got this

![image](https://user-images.githubusercontent.com/73566787/97599310-38203100-19de-11eb-9a3b-0adbdf6a9e79.png)

**Comment by jesburger55** [comment]
I selected "no" for AD and it seems to work now, I will update with your new uploaded code

**Comment by jesburger55** [comment]
Ok your new ps1 seems to work!

big thanks
